title: Biyi
contents:
  - x: 448
    y: 344
    type: link
    path: "/Applications"
  - x: 192
    y: 344
    type: file
    path: biyi.app
code-sign:
  signing-identity: "Developer ID Application: Jianying Li (G83H824X6L)"
