name: biyi_app
description: A convenient translation and dictionary app written in Flutter.
publish_to: "none"
version: 0.5.0+17

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  audioplayers: ^4.0.1
  bot_toast: ^4.0.3
  collection: ^1.17.1
  crypto: ^3.0.3
  dio: ^5.1.2
  easy_localization: ^3.0.1
  easy_localization_loader: ^1.0.1+1
  fluentui_system_icons: ^1.1.200
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hotkey_manager: ^0.1.7
  keypress_simulator: ^0.1.0
  launch_at_startup: ^0.2.2
  ocr_engine_builtin: ^0.1.1
  ocr_engine_youdao: ^0.1.1
  package_info_plus: ^4.0.1
  page_transition: ^2.0.9
  path: ^1.8.3
  path_provider: ^2.0.15
  photo_view: ^0.14.0
  protocol_handler: ^0.1.5
  reorderables: ^0.6.0
  rise_ui:
    git:
      url: https://github.com/leanflutter/rise_ui.git
      path: packages/rise_ui
  screen_capturer: ^0.1.4
  screen_retriever: ^0.1.6
  screen_text_extractor: ^0.1.3
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shortid: ^0.1.2
  sticky_headers: ^0.3.0+2
  translation_engine_baidu: ^0.1.2
  translation_engine_caiyun: ^0.1.2
  translation_engine_deepl: ^0.1.2
  translation_engine_google: ^0.1.2
  translation_engine_iciba: ^0.1.2
  translation_engine_tencent: ^0.1.2
  translation_engine_youdao: ^0.1.2
  tray_manager: ^0.2.0
  uni_ocr: ^0.1.1
  uni_ocr_client: ^0.1.1
  uni_translate: ^0.1.2
  uni_translate_client: ^0.1.2
  url_launcher: ^6.1.11
  vclibs: ^0.1.0
  window_manager: ^0.3.4

dev_dependencies:
  dependency_validator: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false

  assets:
    - assets/images/
    - assets/images/flag_icons/
    - assets/images/ocr_engine_icons/
    - assets/images/translation_engine_icons/
    - assets/translations/

  fonts:
    - family: MiSans
      fonts:
        - asset: assets/fonts/MiSans-Regular.ttf
        - asset: assets/fonts/MiSans-Semibold.ttf
          weight: 600
        - asset: assets/fonts/MiSans-Bold.ttf
          weight: 700
    - family: Roboto Mono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
